script:
- mkdir -p build
- cp {index.html,favicon.ico} build/
- cp -R img build/img
deploy:
  provider: s3
  region: us-east-1
  bucket: rachelandruss.com
  local_dir: build
  skip_cleanup: true
  access_key_id: AKIAIPJMXGHJI6W7NGOQ
  secret_access_key:
    secure: ZeEu9PvLqIoOu2/Z+rbgJ5iSyxyXHyZmf1914j4PcZj8l13e2sq3FWAEeDangG1uhQaZYUnIgRHapnTpACp1cJcbJTU8O+n94ZiLtLKAsxV1+dMcRxc8qOjcQTVHIUpe2bloRTv4HlhtA1fPlPRpYR1bTiSgAwcgR3MMd4Y9BS7edbhc2LJHobzVPBLTDBQwYxEUNCsljIrS6GR3QVuaJtx90Aq3QAVqCh5BYsTuILhJpPmfWYCpxflzemnEd78nkEimSrmh2VDM8RYinlc0TcbP0n8JaoULnuKa/r8qnz3cJSmZmYnnMJbyRWMn3fqtuNwyHA49o1n+YUvG1xJzxnqzKsT6CrT3kWRpN/swH3HAUk6grRYRtLmIU5pm1488u0WFNzHIwhhsVW7liqLy/9sCE+S8kkU7RAxf+zvvLGhh7lobBcQZyGLtrvoVCtetcS3dtV5sPlhrwhQDdkBj+Ur87siMn5ICGgj1En3XCuaQkaVzyby9WwHNlih9wQUito0vUHRPROgs+SYWGxG2tD5rNiBzAd9Kx6tCKorgnqrD2BjzB6G/HGrNiMv5XJVU82X8Utp6El/lqM6GW75/c7Yix90KL45Q9jGCP9gyIVpu5lvHqvxcJI1ok59Ppmgg0e7RWHCwhmrVUdnyHnm6ksOwJbcA5R0K8TG/KAxc4KI=
  acl: public_read
  on:
    repo: russbiggs/wedding
